### ISSUE TITLE
关于 demo 的几个问题

### ISSUE THREAD

**Issue by yqrashawn** [Yumingyuan/Portal_dapp#3]
你好, 我看了一下代码, 有几个问题
1. 在安装了 ConfluxPortal 后, 浏览器页面里有一个 `window.confluxJS` 相当于 `new Conflux(...portal provider...)`, 可以直接使用
2. 这个 demo 主要是调用 ConfluxPortal 签名, 也就是用户私钥存在 portal 里, 通过 `confluxJS` 调用 Portal 签名, 我看代码里还是有私钥存着.

如果有任何问题可以在这里提. 特别是如果觉得 portal 的文档哪里有问题或者不全可以提到 https://github.com/Conflux-Chain/conflux-portal-docs 这里.

**Comment by Yumingyuan** [comment]
好的，我尝试一下，比较奇怪的问题就是：
（1）没有找到调用Portal私钥的库
（2）文档“https://conflux-chain.github.io/conflux-portal-docs/docs/portal/API_Reference/signing_data_with_portal/”中提到了cfx_sign，但我并没有找到。

**Comment by Yumingyuan** [comment]
![image](https://user-images.githubusercontent.com/18106816/85374406-4e693c80-b567-11ea-86e0-76dc1c5797f7.png)
还有这个报错

**Comment by yqrashawn** [comment]
https://conflux-portal-docs.conflux-chain.org/e2e_test_demo/
这里有个 demo 是 e2e 测试用的, 里面包含了部分签名的调用方法和 account 调用的方法
对应的源码在 https://github.com/Conflux-Chain/conflux-portal-docs/blob/master/e2e_test_demo/contract.js
也可以浏览器中直接查看, 代码是没压缩的, 里面有 account 和 `cfx_sign` 相关的代码.

portal 不会直接提供私钥给 dapp 的开发者, dapp 的开发者可以直接调用[各种 rpc 方法](https://developer.conflux-chain.org/docs/conflux-doc/docs/json_rpc), 需要私钥签名的方法 portal 会自动请求用户授权.

**Comment by Yumingyuan** [comment]
好的，非常感谢，我赶紧好好试试，后续有进展持续跟您汇报

**Comment by Yumingyuan** [comment]
我初步扫了一下代码，看起来签名就好像在和一个合约交互，是这样吗

**Comment by yqrashawn** [comment]
不是的, 比如[这里](https://github.com/Conflux-Chain/conflux-portal-docs/blob/7cff92b1e26feb07b53a0466260e82e0436e79a6/e2e_test_demo/contract.js#L676), 签名实际上是调用了一个 `cfx_sign` rpc 方法. [这里](https://github.com/Conflux-Chain/conflux-portal-docs/blob/7cff92b1e26feb07b53a0466260e82e0436e79a6/e2e_test_demo/contract.js#L740)也一样.

**Comment by Yumingyuan** [comment]
您好，内容已更新！

**Comment by Yumingyuan** [comment]
> 不是的, 比如[这里](https://github.com/Conflux-Chain/conflux-portal-docs/blob/7cff92b1e26feb07b53a0466260e82e0436e79a6/e2e_test_demo/contract.js#L676), 签名实际上是调用了一个 `cfx_sign` rpc 方法. [这里](https://github.com/Conflux-Chain/conflux-portal-docs/blob/7cff92b1e26feb07b53a0466260e82e0436e79a6/e2e_test_demo/contract.js#L740)也一样.

您好内容已更新！

**Comment by yqrashawn** [comment]
我详细看了一下代码
1. [这里](https://github.com/Yumingyuan/Portal_dapp/blob/0cd5ccdce8eb5b1cd2a9e842108f09ad6eaac85c/index.js#L1) 两个不用的库可以删掉
2. [这里](https://github.com/Yumingyuan/Portal_dapp/blob/0cd5ccdce8eb5b1cd2a9e842108f09ad6eaac85c/index.js#L39) sha3 只是实例怎么对待签名的 message 做 sha3 处理, 不用调用 portal
3. ethjs personal sign, sign typed data v4, sign typed data with ethjs 可以去掉
4. sign typed data v3 可以和 sign typed data 合为一个, 叫 sign typed data (v3) 这样
5. recover 那个可以先调 cfx_sign 然后把签完名的 signature 和 sha3 处理的 message hash 传给 [js-conflux-sdk 的 Message.recover 方法获得 publicKey](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/api.md#messagerecover-)

**Comment by Yumingyuan** [comment]
> 我详细看了一下代码
> 
> 1. [这里](https://github.com/Yumingyuan/Portal_dapp/blob/0cd5ccdce8eb5b1cd2a9e842108f09ad6eaac85c/index.js#L1) 两个不用的库可以删掉
> 2. [这里](https://github.com/Yumingyuan/Portal_dapp/blob/0cd5ccdce8eb5b1cd2a9e842108f09ad6eaac85c/index.js#L39) sha3 只是实例怎么对待签名的 message 做 sha3 处理, 不用调用 portal
> 3. ethjs personal sign, sign typed data v4, sign typed data with ethjs 可以去掉
> 4. sign typed data v3 可以和 sign typed data 合为一个, 叫 sign typed data (v3) 这样
> 5. recover 那个可以先调 cfx_sign 然后把签完名的 signature 和 sha3 处理的 message hash 传给 [js-conflux-sdk 的 Message.recover 方法获得 publicKey](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/api.md#messagerecover-)

收到，今日晚点时间完善，谢谢

**Comment by Yumingyuan** [comment]
> 我详细看了一下代码
> 
> 1. [这里](https://github.com/Yumingyuan/Portal_dapp/blob/0cd5ccdce8eb5b1cd2a9e842108f09ad6eaac85c/index.js#L1) 两个不用的库可以删掉
> 2. [这里](https://github.com/Yumingyuan/Portal_dapp/blob/0cd5ccdce8eb5b1cd2a9e842108f09ad6eaac85c/index.js#L39) sha3 只是实例怎么对待签名的 message 做 sha3 处理, 不用调用 portal
> 3. ethjs personal sign, sign typed data v4, sign typed data with ethjs 可以去掉
> 4. sign typed data v3 可以和 sign typed data 合为一个, 叫 sign typed data (v3) 这样
> 5. recover 那个可以先调 cfx_sign 然后把签完名的 signature 和 sha3 处理的 message hash 传给 [js-conflux-sdk 的 Message.recover 方法获得 publicKey](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/api.md#messagerecover-)

另您所描述的：sha3 只是实例怎么对待签名的 message 做 sha3 处理, 不用调用 portal，我有点没太理解，那部分确实没吊用portal，后续有调用，在https://github.com/Yumingyuan/Portal_dapp/blob/0cd5ccdce8eb5b1cd2a9e842108f09ad6eaac85c/index.js#L93

**Comment by yqrashawn** [comment]
这里 sha3 是向用户演示怎样对 message 进行 sha3 处理.

因为像 [js-conflux-sdk 的 Message.sign 函数](https://github.com/Conflux-Chain/js-conflux-sdk/blob/aa605373099f23993350c73143faf692ad9461ea/src/Message.js#L19) 就要求填 `messageHash` 的 `string` 或 `buffer` 格式. 这里的 `messageHash` 就是 sha3 处理后的 message.

**Comment by Yumingyuan** [comment]
> 这里 sha3 是向用户演示怎样对 message 进行 sha3 处理.
> 
> 因为像 [js-conflux-sdk 的 Message.sign 函数](https://github.com/Conflux-Chain/js-conflux-sdk/blob/aa605373099f23993350c73143faf692ad9461ea/src/Message.js#L19) 就要求填 `messageHash` 的 `string` 或 `buffer` 格式. 这里的 `messageHash` 就是 sha3 处理后的 message.

恩恩，那请问我应该怎么优化一下呢，是取消sha3，调用Message.sign吗

**Comment by Yumingyuan** [comment]
> `messageHash`

问题就在于如果用Message.sign的话，又要自定义私钥了看起来

**Comment by Yumingyuan** [comment]
> 这里 sha3 是向用户演示怎样对 message 进行 sha3 处理.
> 
> 因为像 [js-conflux-sdk 的 Message.sign 函数](https://github.com/Conflux-Chain/js-conflux-sdk/blob/aa605373099f23993350c73143faf692ad9461ea/src/Message.js#L19) 就要求填 `messageHash` 的 `string` 或 `buffer` 格式. 这里的 `messageHash` 就是 sha3 处理后的 message.

**Comment by Yumingyuan** [comment]
> 这里 sha3 是向用户演示怎样对 message 进行 sha3 处理.
> 
> 因为像 [js-conflux-sdk 的 Message.sign 函数](https://github.com/Conflux-Chain/js-conflux-sdk/blob/aa605373099f23993350c73143faf692ad9461ea/src/Message.js#L19) 就要求填 `messageHash` 的 `string` 或 `buffer` 格式. 这里的 `messageHash` 就是 sha3 处理后的 message.

您好，已更新！

**Comment by Yumingyuan** [comment]
> 这里 sha3 是向用户演示怎样对 message 进行 sha3 处理.
> 
> 因为像 [js-conflux-sdk 的 Message.sign 函数](https://github.com/Conflux-Chain/js-conflux-sdk/blob/aa605373099f23993350c73143faf692ad9461ea/src/Message.js#L19) 就要求填 `messageHash` 的 `string` 或 `buffer` 格式. 这里的 `messageHash` 就是 sha3 处理后的 message.

hello

**Comment by yqrashawn** [comment]
你好, 我们内部讨论了一下, 现在并没有一个确定推荐用户使用的签名方法, 所以 demo 暂时不会放在 portal 文档里, 不过现阶段的 demo 已经算是完成了.
